version: '3.0'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: node_hex
      MYSQL_ROOT_PASSWORD: hexdev
    ports:
      - '3306:3306'
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/