apps:
  - name: 'seed'
    script: './dist/app.js'
    out_file: './logs/seed.log'
    watch: false
    env_prd:
      ENV: 'prd'
      API: "express"
      DB: "mongodb"
      PORT: 5001
      DB_CONN: 'mongodb://hexdev:hexdev@localhost:27017'
      DB_NAME: 'node_hex'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'hexdev'
      MYSQL_PORT: 3306
      MYSQL_CONN: 'localhost'
